### ISSUE TITLE
Cannot generate nonpeak matrix correctly

### ISSUE THREAD

**Issue by Zhixuan-Jing** [JSB-UCLA/scReadSim#2]
Dear developers,

I am following your instruction in the website to do simulation of the sample data. However, in scATAC_CreateFeatureSets function, there is an error showing that "Fail to create complementary feature set". The problem is shown as follow. The code is exactly the same as which appears in the website. Do you have any idea about that?
<img width="468" alt="1678783860702(1)" src="https://user-images.githubusercontent.com/57510261/224946733-33eaf5bd-5dd8-49da-b709-26490b1714cb.png">
<img width="882" alt="1678783929750" src="https://user-images.githubusercontent.com/57510261/224947041-19136fd6-dafb-44f8-8599-9cf8bf54ff58.png">

**Comment by Dominic7227** [comment]
Hmm, this is strange. I can not reproduce your error: I just run a test on a different machine and followed the tutorial and it works fine. 

Would you like to post here your `scReadSim_MACS3_LessStringent_peaks.narrowPeak` and `scReadSim_MACS3.nonpeak.tmp.bed` if existing? Those files are the intermediate files used to generate complementary feature set. I can look into these files and test it for you directly on my end.

**Comment by Zhixuan-Jing** [comment]
Here are these two files. Since they are unsupported file type I changed the minto txt file at the end of file name. 
[scReadSim_MACS3_LessStringent_peaks.narrowPeak.txt](https://github.com/JSB-UCLA/scReadSim/files/10975094/scReadSim_MACS3_LessStringent_peaks.narrowPeak.txt)
[scReadSim_MACS3.nonpeak.tmp.bed.txt](https://github.com/JSB-UCLA/scReadSim/files/10975095/scReadSim_MACS3.nonpeak.tmp.bed.txt)

**Comment by Dominic7227** [comment]
Hi Zhixuan, sorry for the later response. I looked into your files and they are absolutely right. Could you check the following things for me: 
- cd into your output directory when you run these analysis (basically `outdirectory ` you specified in the analysis). 
- Make sure you have scReadSim_MACS3.nonpeak.tmp.bed, Peak_NonPeaks_Union.bed, and genome_size_selected.txt in your current directory.
- Generate feature sets manually by running
  1. `bedtools complement -i scReadSim_MACS3.nonpeak.tmp.bed -g genome_size_selected.txt > scReadSim.MACS3.nonpeak.bed`
  2. `bedtools complement -i Peak_NonPeaks_Union.bed -g genome_size_selected.txt > scReadSim.grayareas.bed`

So these two lines generate non-peaks and gray areas in the function `scATAC_CreateFeatureSets`. I wonder if these two lines caused the trouble.

**Comment by Zhixuan-Jing** [comment]
This problem is fixed now thanks for your support.
