### ISSUE TITLE
Problem on "operation not supported"

### ISSUE THREAD

**Issue by Zhixuan-Jing** [JSB-UCLA/scReadSim#3]
Dear developers,

Recently I was testing scReadSim on server, but have one difficulty: when I run GenerateBAMCoord function, it always appears that "operation not supported". Even if I restart and rerun the program it still remains. The screenshot is attached below. Thanks for your help and looking forward to your reply.
<img width="411" alt="1679638093516" src="https://user-images.githubusercontent.com/57510261/227438651-61d7ab35-7149-4726-b03e-f46a814e98be.png">

**Comment by Dominic7227** [comment]
Thanks for notifying us of the error! We haven't met this error before. Could you please present a full screenshot of all output messages by function `GenerateBAMCoord` ? I will need more information to tackle this issue.

**Comment by Zhixuan-Jing** [comment]
The screenshot for code and output are attached below
<img width="1234" alt="1679707258195" src="https://user-images.githubusercontent.com/57510261/227675663-27d3b894-f3e9-4af5-b1a4-42ee1868030f.png">
<img width="1090" alt="1679707328628" src="https://user-images.githubusercontent.com/57510261/227675968-26c24a5e-5a69-423b-82ec-7b591542e778.png">

**Comment by Dominic7227** [comment]
Okay, the issue relates to the pandas dataframe.to_csv function when scReadSim tries to store the reads. The post below says that the potential reason might be that you do not have the write permissions for that directory. You may want to 
**i)**  test storing other random data frames using pd.to_csv **into this directory** to see if a permission issue does exist, 
**ii)** if so, modify your permissions to that directory, or use other directories with permissions.

https://stackoverflow.com/questions/56609051/what-is-oserror-errno-95-operation-not-supported-for-pandas-to-csv-on-colab

**Comment by Zhixuan-Jing** [comment]
Dear Dominic,
Thanks for suggestion. I have tried to test the permissioon, but there is no problem with it. The test code is shown below.
<img width="762" alt="1679807627078" src="https://user-images.githubusercontent.com/57510261/227756806-528f38ca-8140-48b5-a5d0-72dae6e68de6.png">

**Comment by Dominic7227** [comment]
Thanks for letting me know! Could you please help try the following codes (basically create an empty csv file before you write the df to the csv)?
```
with open("%s/testingXXXXXXX.csv" % outdirectory, 'w') as f_1:
    pass
df.to_csv("%s/testingXXXXXXX.csv" % outdirectory,  header=None, index=None, sep="\t", mode="a")
```

I'm not quite sure what happened on your end, did you also try to write the reads into a different directory and see if that works?
