### ISSUE TITLE
Feature Question on Count Matrix Generation in scReadSim

### ISSUE THREAD

**Issue by csweichen** [JSB-UCLA/scReadSim#5]
Hello,

I recently used scReadSim to generate single-cell RNA reads and found it very useful. I am trying to measure the accuracy of gene abundance quantification with the synthetic reads. However, following the tutorial, I ended up with a count matrix mapping cells to chromosomes and positional intervals.

Is it possible to generate a count matrix mapping cells to genes instead? This would be more precise for my purpose of evaluating gene abundance quantification.

Thank you in advance for your assistance.

Sincerely,
Brian

**Comment by Dominic7227** [comment]
Hi Brian,

Thank you for your question! The current scReadSim implementation does not support the gene-level counts. We will have our extended version that can tackle this issue coming out shortly.
