### ISSUE TITLE
Seurat Error During Tutorial

### ISSUE THREAD

**Issue by RachelPolak** [JSB-UCLA/scReadSim#6]
Hello, I have an issue that I was able to solve but wanted to bring your attention to. 

While following the tutorial for scRNAseq, I ran into the following error while generating the synthetic count matrix.

RRuntimeError: Error in initialize(value, ...) : 
  invalid name for slot of class “Assay5”: verbose

I used the same command from the tutorial:
GenerateSyntheticCount.scRNA_GenerateSyntheticCount(count_mat_filename=UMI_gene_count_mat_filename, directory=outdirectory, outdirectory=outdirectory, doub_classification_label_file="/path/to/doublet_classification.Rdata")

When I searched for similar errors, they appeared to come from Seurat, and have to do with changes to functions made in v5. I had not previously installed Seurat, leaving it to the automatic installation, which I assume was the newest version. Downgrading my installation of Seurat to v4.4 fixed it!

**Comment by Dominic7227** [comment]
Thank you for bringing this to us! I will look into it and make modifications.
